version: '3'
services:
  todo:
    build: .
    volumes:
      - type: bind
        source: ./DockerCode
        target: /app/
    ports:
      - 3000:80
  web:
    image: php:apache
    volumes:
      - type: bind
        source: ./DockerCode
        target: /app/
    ports:
      - 3001:80
    depends_on:
      - todo
  
