version: '3'
services:
  todo:
    build: .
    volumes:
      - . : /app/
    ports:
      - 3000:80
  web:
    image: php:apache
    volumes:
      - .:/var/www/html
    ports:
      - 3001:80
    depends_on:
      - todo